dist: xenial

language: python

services: mysql

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - DJANGO_VERSION=3.0.5

before_script:
  - mysql -e 'CREATE DATABASE enseign;'
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test