/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Scolendar);
  }
}(this, function(expect, Scolendar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Scolendar.StudentsApi();
  });

  describe('(package)', function() {
    describe('StudentsApi', function() {
      describe('studentsDelete', function() {
        it('should call studentsDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsDelete call and complete the assertions
          /*
          var iDRequest = new Scolendar.IDRequest();

          instance.studentsDelete(iDRequest, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.SimpleSuccessResponse);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsGet', function() {
        it('should call studentsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsGet call and complete the assertions
          /*
          var opts = {};
          opts.query = "query_example";
          opts.page = 56;

          instance.studentsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.StudentListResponse);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");
            expect(data.total).to.be.a('number');
            expect(data.total).to.be(100);
            {
              let dataCtr = data.students;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Scolendar.StudentListResponseStudents);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.firstName).to.be.a('string');
                expect(data.firstName).to.be("Fabien");
                expect(data.lastName).to.be.a('string');
                expect(data.lastName).to.be("Vidal");
                expect(data.className).to.be.a('string');
                expect(data.className).to.be("L3 Informatique");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsIdGet', function() {
        it('should call studentsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsIdGet call and complete the assertions
          /*
          var id = 56;

          instance.studentsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.StudentResponse);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");
            expect(data.student).to.be.a(Scolendar.StudentResponseStudent);
                  expect(data.student.firstName).to.be.a('string');
              expect(data.student.firstName).to.be("Fabien");
              expect(data.student.lastName).to.be.a('string');
              expect(data.student.lastName).to.be("Vidal");
              expect(data.student.username).to.be.a('string');
              expect(data.student.username).to.be("road.buddy");
              expect(data.student.totalHours).to.be.a('number');
              expect(data.student.totalHours).to.be(58);
              {
                let dataCtr = data.student.subjects;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Scolendar.StudentResponseStudentSubjects);
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("Anglais");
                  expect(data.group).to.be.a('string');
                  expect(data.group).to.be("Groupe 1");
  
                        }
              }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsIdOccupanciesGet', function() {
        it('should call studentsIdOccupanciesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsIdOccupanciesGet call and complete the assertions
          /*
          var id = 56;
          var opts = {};
          opts.start = 56;
          opts.end = 56;
          opts.occupanciesPerDay = 56;

          instance.studentsIdOccupanciesGet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.Occupancies);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");
            {
              let dataCtr = data.days;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Scolendar.OccupanciesDays);
                expect(data._date).to.be.a('string');
                expect(data._date).to.be("01-05-2020");
                {
                  let dataCtr = data.occupancies;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Scolendar.OccupanciesOccupancies);
                    expect(data.id).to.be.a('number');
                    expect(data.id).to.be(0);
                    expect(data.classroomName).to.be.a('string');
                    expect(data.classroomName).to.be("B.001");
                    expect(data.groupName).to.be.a('string');
                    expect(data.groupName).to.be("Groupe 1");
                    expect(data.subjectName).to.be.a('string');
                    expect(data.subjectName).to.be("Algorithmique");
                    expect(data.teacherName).to.be.a('string');
                    expect(data.teacherName).to.be("mylan chevalier");
                    expect(data.start).to.be.a('number');
                    expect(data.start).to.be(1587776227);
                    expect(data.end).to.be.a('number');
                    expect(data.end).to.be(1587779827);
                    expect(data.occupancyType).to.be.a(Scolendar.OccupancyType);
                        expect(data.className).to.be.a('string');
                    expect(data.className).to.be("L3 Informatique");
                    expect(data.name).to.be.a('string');
                    expect(data.name).to.be("Algorithmique CM Groupe 1");
    
                          }
                }

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsIdPut', function() {
        it('should call studentsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsIdPut call and complete the assertions
          /*
          var id = 56;
          var studentUpdateRequest = new Scolendar.StudentUpdateRequest();
          studentUpdateRequest.firstName = "mylan";
          studentUpdateRequest.lastName = "chevalier";
          studentUpdateRequest.classId = 0;
          studentUpdateRequest.password = "newpassword";

          instance.studentsIdPut(id, studentUpdateRequest, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.SimpleSuccessResponse);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsIdSubjectsGet', function() {
        it('should call studentsIdSubjectsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsIdSubjectsGet call and complete the assertions
          /*
          var id = 56;

          instance.studentsIdSubjectsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.StudentSubjects);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");
            {
              let dataCtr = data.subjects;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Scolendar.StudentSubjectsSubjects);
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("PPPE");
                expect(data.className).to.be.a('string');
                expect(data.className).to.be("L3 Informatique");
                {
                  let dataCtr = data.teachers;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Scolendar.TeacherSubjectsTeachers);
                    expect(data.firstName).to.be.a('string');
                    expect(data.firstName).to.be("Butch");
                    expect(data.lastName).to.be.a('string');
                    expect(data.lastName).to.be("Cranky");
                    expect(data.inCharge).to.be.a('boolean');
                    expect(data.inCharge).to.be(true);
                    expect(data.email).to.be.a('string');
                    expect(data.email).to.be("butch.cranky@nook.mail");
                    expect(data.phoneNumber).to.be.a('string');
                    expect(data.phoneNumber).to.be("06 71 55 50 11");
    
                          }
                }
                {
                  let dataCtr = data.groups;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Scolendar.StudentSubjectsGroups);
                    expect(data.name).to.be.a('string');
                    expect(data.name).to.be("Groupe 1");
                    expect(data.count).to.be.a('number');
                    expect(data.count).to.be(22);
                    expect(data.isStudentGroup).to.be.a('boolean');
                    expect(data.isStudentGroup).to.be(false);
    
                          }
                }

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('studentsPost', function() {
        it('should call studentsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for studentsPost call and complete the assertions
          /*
          var studentCreationRequest = new Scolendar.StudentCreationRequest();
          studentCreationRequest.firstName = "fabien";
          studentCreationRequest.lastName = "Vidal";
          studentCreationRequest.classId = 0;

          instance.studentsPost(studentCreationRequest, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Scolendar.AccountCreatedResponse);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("success");
            expect(data.username).to.be.a('string');
            expect(data.username).to.be("azure_diamong");
            expect(data.password).to.be.a('string');
            expect(data.password).to.be("n5l*2#01@");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
