/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ClassWithId'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClassWithId'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.ClassesList = factory(root.Scolendar.ApiClient, root.Scolendar.ClassWithId);
  }
}(this, function(ApiClient, ClassWithId) {
  'use strict';

  /**
   * The ClassesList model module.
   * @module model/ClassesList
   * @version v1
   */

  /**
   * Constructs a new <code>ClassesList</code>.
   * @alias module:model/ClassesList
   * @class
   * @param status {String} 
   * @param total {Number} 
   * @param classes {Array.<module:model/ClassWithId>} 
   */
  var exports = function(status, total, classes) {
    this.status = status;
    this.total = total;
    this.classes = classes;
  };

  /**
   * Constructs a <code>ClassesList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClassesList} obj Optional instance to populate.
   * @return {module:model/ClassesList} The populated <code>ClassesList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('classes'))
        obj.classes = ApiClient.convertToType(data['classes'], [ClassWithId]);
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  /**
   * @member {Array.<module:model/ClassWithId>} classes
   */
  exports.prototype.classes = undefined;

  return exports;

}));
