/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelClass'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelClass'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.ClassResponse = factory(root.Scolendar.ApiClient, root.Scolendar.ModelClass);
  }
}(this, function(ApiClient, ModelClass) {
  'use strict';

  /**
   * The ClassResponse model module.
   * @module model/ClassResponse
   * @version v1
   */

  /**
   * Constructs a new <code>ClassResponse</code>.
   * @alias module:model/ClassResponse
   * @class
   * @param status {String} 
   * @param _class {module:model/ModelClass} 
   * @param totalService {Number} 
   */
  var exports = function(status, _class, totalService) {
    this.status = status;
    this._class = _class;
    this.totalService = totalService;
  };

  /**
   * Constructs a <code>ClassResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClassResponse} obj Optional instance to populate.
   * @return {module:model/ClassResponse} The populated <code>ClassResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('class'))
        obj._class = ModelClass.constructFromObject(data['class']);
      if (data.hasOwnProperty('total_service'))
        obj.totalService = ApiClient.convertToType(data['total_service'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {module:model/ModelClass} _class
   */
  exports.prototype._class = undefined;

  /**
   * @member {Number} totalService
   */
  exports.prototype.totalService = undefined;

  return exports;

}));
