/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OccupancyType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OccupancyType'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.OccupanciesCreationRequest = factory(root.Scolendar.ApiClient, root.Scolendar.OccupancyType);
  }
}(this, function(ApiClient, OccupancyType) {
  'use strict';

  /**
   * The OccupanciesCreationRequest model module.
   * @module model/OccupanciesCreationRequest
   * @version v1
   */

  /**
   * Constructs a new <code>OccupanciesCreationRequest</code>.
   * @alias module:model/OccupanciesCreationRequest
   * @class
   * @param classroomId {Number} 
   * @param start {Number} 
   * @param end {Number} 
   * @param name {String} 
   * @param occupancyType {module:model/OccupancyType} 
   * @param teacherId {Number} 
   */
  var exports = function(classroomId, start, end, name, occupancyType, teacherId) {
    this.classroomId = classroomId;
    this.start = start;
    this.end = end;
    this.name = name;
    this.occupancyType = occupancyType;
    this.teacherId = teacherId;
  };

  /**
   * Constructs a <code>OccupanciesCreationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OccupanciesCreationRequest} obj Optional instance to populate.
   * @return {module:model/OccupanciesCreationRequest} The populated <code>OccupanciesCreationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('classroom_id'))
        obj.classroomId = ApiClient.convertToType(data['classroom_id'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Number');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('occupancy_type'))
        obj.occupancyType = OccupancyType.constructFromObject(data['occupancy_type']);
      if (data.hasOwnProperty('teacher_id'))
        obj.teacherId = ApiClient.convertToType(data['teacher_id'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} classroomId
   */
  exports.prototype.classroomId = undefined;

  /**
   * @member {Number} start
   */
  exports.prototype.start = undefined;

  /**
   * @member {Number} end
   */
  exports.prototype.end = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {module:model/OccupancyType} occupancyType
   */
  exports.prototype.occupancyType = undefined;

  /**
   * @member {Number} teacherId
   */
  exports.prototype.teacherId = undefined;

  return exports;

}));
