/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OccupanciesOccupancies'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OccupanciesOccupancies'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.OccupanciesDays = factory(root.Scolendar.ApiClient, root.Scolendar.OccupanciesOccupancies);
  }
}(this, function(ApiClient, OccupanciesOccupancies) {
  'use strict';

  /**
   * The OccupanciesDays model module.
   * @module model/OccupanciesDays
   * @version v1
   */

  /**
   * Constructs a new <code>OccupanciesDays</code>.
   * @alias module:model/OccupanciesDays
   * @class
   * @param _date {String} 
   * @param occupancies {Array.<module:model/OccupanciesOccupancies>} 
   */
  var exports = function(_date, occupancies) {
    this._date = _date;
    this.occupancies = occupancies;
  };

  /**
   * Constructs a <code>OccupanciesDays</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OccupanciesDays} obj Optional instance to populate.
   * @return {module:model/OccupanciesDays} The populated <code>OccupanciesDays</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('occupancies'))
        obj.occupancies = ApiClient.convertToType(data['occupancies'], [OccupanciesOccupancies]);
    }
    return obj;
  }

  /**
   * @member {String} _date
   */
  exports.prototype._date = undefined;

  /**
   * @member {Array.<module:model/OccupanciesOccupancies>} occupancies
   */
  exports.prototype.occupancies = undefined;

  return exports;

}));
