/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OccupancyType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OccupancyType'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.OccupanciesOccupancies = factory(root.Scolendar.ApiClient, root.Scolendar.OccupancyType);
  }
}(this, function(ApiClient, OccupancyType) {
  'use strict';

  /**
   * The OccupanciesOccupancies model module.
   * @module model/OccupanciesOccupancies
   * @version v1
   */

  /**
   * Constructs a new <code>OccupanciesOccupancies</code>.
   * @alias module:model/OccupanciesOccupancies
   * @class
   * @param id {Number} 
   * @param classroomName {String} 
   * @param groupName {String} 
   * @param subjectName {String} 
   * @param teacherName {String} 
   * @param start {Number} 
   * @param end {Number} 
   * @param occupancyType {module:model/OccupancyType} 
   * @param className {String} 
   * @param name {String} 
   */
  var exports = function(id, classroomName, groupName, subjectName, teacherName, start, end, occupancyType, className, name) {
    this.id = id;
    this.classroomName = classroomName;
    this.groupName = groupName;
    this.subjectName = subjectName;
    this.teacherName = teacherName;
    this.start = start;
    this.end = end;
    this.occupancyType = occupancyType;
    this.className = className;
    this.name = name;
  };

  /**
   * Constructs a <code>OccupanciesOccupancies</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OccupanciesOccupancies} obj Optional instance to populate.
   * @return {module:model/OccupanciesOccupancies} The populated <code>OccupanciesOccupancies</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('classroom_name'))
        obj.classroomName = ApiClient.convertToType(data['classroom_name'], 'String');
      if (data.hasOwnProperty('group_name'))
        obj.groupName = ApiClient.convertToType(data['group_name'], 'String');
      if (data.hasOwnProperty('subject_name'))
        obj.subjectName = ApiClient.convertToType(data['subject_name'], 'String');
      if (data.hasOwnProperty('teacher_name'))
        obj.teacherName = ApiClient.convertToType(data['teacher_name'], 'String');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Number');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Number');
      if (data.hasOwnProperty('occupancy_type'))
        obj.occupancyType = OccupancyType.constructFromObject(data['occupancy_type']);
      if (data.hasOwnProperty('class_name'))
        obj.className = ApiClient.convertToType(data['class_name'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} classroomName
   */
  exports.prototype.classroomName = undefined;

  /**
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * @member {String} subjectName
   */
  exports.prototype.subjectName = undefined;

  /**
   * @member {String} teacherName
   */
  exports.prototype.teacherName = undefined;

  /**
   * @member {Number} start
   */
  exports.prototype.start = undefined;

  /**
   * @member {Number} end
   */
  exports.prototype.end = undefined;

  /**
   * @member {module:model/OccupancyType} occupancyType
   */
  exports.prototype.occupancyType = undefined;

  /**
   * @member {String} className
   */
  exports.prototype.className = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  return exports;

}));
