/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProfileRecentModificationsOccupancy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProfileRecentModificationsOccupancy'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.ProfileRecentModificationsModifications = factory(root.Scolendar.ApiClient, root.Scolendar.ProfileRecentModificationsOccupancy);
  }
}(this, function(ApiClient, ProfileRecentModificationsOccupancy) {
  'use strict';

  /**
   * The ProfileRecentModificationsModifications model module.
   * @module model/ProfileRecentModificationsModifications
   * @version v1
   */

  /**
   * Constructs a new <code>ProfileRecentModificationsModifications</code>.
   * @alias module:model/ProfileRecentModificationsModifications
   * @class
   * @param modificationType {module:model/ProfileRecentModificationsModifications.ModificationTypeEnum} 
   * @param modificationTimestamp {Number} 
   * @param occupancy {module:model/ProfileRecentModificationsOccupancy} 
   */
  var exports = function(modificationType, modificationTimestamp, occupancy) {
    this.modificationType = modificationType;
    this.modificationTimestamp = modificationTimestamp;
    this.occupancy = occupancy;
  };

  /**
   * Constructs a <code>ProfileRecentModificationsModifications</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileRecentModificationsModifications} obj Optional instance to populate.
   * @return {module:model/ProfileRecentModificationsModifications} The populated <code>ProfileRecentModificationsModifications</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('modification_type'))
        obj.modificationType = ApiClient.convertToType(data['modification_type'], 'String');
      if (data.hasOwnProperty('modification_timestamp'))
        obj.modificationTimestamp = ApiClient.convertToType(data['modification_timestamp'], 'Number');
      if (data.hasOwnProperty('occupancy'))
        obj.occupancy = ProfileRecentModificationsOccupancy.constructFromObject(data['occupancy']);
    }
    return obj;
  }

  /**
   * @member {module:model/ProfileRecentModificationsModifications.ModificationTypeEnum} modificationType
   */
  exports.prototype.modificationType = undefined;

  /**
   * @member {Number} modificationTimestamp
   */
  exports.prototype.modificationTimestamp = undefined;

  /**
   * @member {module:model/ProfileRecentModificationsOccupancy} occupancy
   */
  exports.prototype.occupancy = undefined;


  /**
   * Allowed values for the <code>modificationType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ModificationTypeEnum = {
    /**
     * value: "CREATE"
     * @const
     */
    CREATE: "CREATE",

    /**
     * value: "EDIT"
     * @const
     */
    EDIT: "EDIT",

    /**
     * value: "DELETE"
     * @const
     */
    DELETE: "DELETE"
  };

  return exports;

}));
