/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StudentResponseStudentSubjects'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StudentResponseStudentSubjects'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.StudentResponseStudent = factory(root.Scolendar.ApiClient, root.Scolendar.StudentResponseStudentSubjects);
  }
}(this, function(ApiClient, StudentResponseStudentSubjects) {
  'use strict';

  /**
   * The StudentResponseStudent model module.
   * @module model/StudentResponseStudent
   * @version v1
   */

  /**
   * Constructs a new <code>StudentResponseStudent</code>.
   * @alias module:model/StudentResponseStudent
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param username {String} 
   * @param totalHours {Number} 
   * @param subjects {Array.<module:model/StudentResponseStudentSubjects>} 
   */
  var exports = function(firstName, lastName, username, totalHours, subjects) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.username = username;
    this.totalHours = totalHours;
    this.subjects = subjects;
  };

  /**
   * Constructs a <code>StudentResponseStudent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StudentResponseStudent} obj Optional instance to populate.
   * @return {module:model/StudentResponseStudent} The populated <code>StudentResponseStudent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('total_hours'))
        obj.totalHours = ApiClient.convertToType(data['total_hours'], 'Number');
      if (data.hasOwnProperty('subjects'))
        obj.subjects = ApiClient.convertToType(data['subjects'], [StudentResponseStudentSubjects]);
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {Number} totalHours
   */
  exports.prototype.totalHours = undefined;

  /**
   * @member {Array.<module:model/StudentResponseStudentSubjects>} subjects
   */
  exports.prototype.subjects = undefined;

  return exports;

}));
