/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SubjectListResponseSubjects'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SubjectListResponseSubjects'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.SubjectListResponse = factory(root.Scolendar.ApiClient, root.Scolendar.SubjectListResponseSubjects);
  }
}(this, function(ApiClient, SubjectListResponseSubjects) {
  'use strict';

  /**
   * The SubjectListResponse model module.
   * @module model/SubjectListResponse
   * @version v1
   */

  /**
   * Constructs a new <code>SubjectListResponse</code>.
   * @alias module:model/SubjectListResponse
   * @class
   * @param status {String} 
   * @param total {Number} Total number of students.
   * @param subjects {Array.<module:model/SubjectListResponseSubjects>} 
   */
  var exports = function(status, total, subjects) {
    this.status = status;
    this.total = total;
    this.subjects = subjects;
  };

  /**
   * Constructs a <code>SubjectListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubjectListResponse} obj Optional instance to populate.
   * @return {module:model/SubjectListResponse} The populated <code>SubjectListResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('subjects'))
        obj.subjects = ApiClient.convertToType(data['subjects'], [SubjectListResponseSubjects]);
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * Total number of students.
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  /**
   * @member {Array.<module:model/SubjectListResponseSubjects>} subjects
   */
  exports.prototype.subjects = undefined;

  return exports;

}));
