/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Role'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Role'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.SuccessfulLoginResponseUser = factory(root.Scolendar.ApiClient, root.Scolendar.Role);
  }
}(this, function(ApiClient, Role) {
  'use strict';

  /**
   * The SuccessfulLoginResponseUser model module.
   * @module model/SuccessfulLoginResponseUser
   * @version v1
   */

  /**
   * Constructs a new <code>SuccessfulLoginResponseUser</code>.
   * @alias module:model/SuccessfulLoginResponseUser
   * @class
   * @param id {Number} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param kind {module:model/Role} 
   */
  var exports = function(id, firstName, lastName, kind) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.kind = kind;
  };

  /**
   * Constructs a <code>SuccessfulLoginResponseUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuccessfulLoginResponseUser} obj Optional instance to populate.
   * @return {module:model/SuccessfulLoginResponseUser} The populated <code>SuccessfulLoginResponseUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = Role.constructFromObject(data['kind']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {module:model/Role} kind
   */
  exports.prototype.kind = undefined;

  return exports;

}));
