/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.TeacherSubjectsTeachers = factory(root.Scolendar.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TeacherSubjectsTeachers model module.
   * @module model/TeacherSubjectsTeachers
   * @version v1
   */

  /**
   * Constructs a new <code>TeacherSubjectsTeachers</code>.
   * @alias module:model/TeacherSubjectsTeachers
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param inCharge {Boolean} 
   * @param email {String} 
   * @param phoneNumber {String} 
   */
  var exports = function(firstName, lastName, inCharge, email, phoneNumber) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.inCharge = inCharge;
    this.email = email;
    this.phoneNumber = phoneNumber;
  };

  /**
   * Constructs a <code>TeacherSubjectsTeachers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeacherSubjectsTeachers} obj Optional instance to populate.
   * @return {module:model/TeacherSubjectsTeachers} The populated <code>TeacherSubjectsTeachers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('in_charge'))
        obj.inCharge = ApiClient.convertToType(data['in_charge'], 'Boolean');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {Boolean} inCharge
   */
  exports.prototype.inCharge = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} phoneNumber
   */
  exports.prototype.phoneNumber = undefined;

  return exports;

}));
