/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Rank', 'model/TeacherResponseTeacherServices'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Rank'), require('./TeacherResponseTeacherServices'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.TeacherResponseTeacher = factory(root.Scolendar.ApiClient, root.Scolendar.Rank, root.Scolendar.TeacherResponseTeacherServices);
  }
}(this, function(ApiClient, Rank, TeacherResponseTeacherServices) {
  'use strict';

  /**
   * The TeacherResponseTeacher model module.
   * @module model/TeacherResponseTeacher
   * @version v1
   */

  /**
   * Constructs a new <code>TeacherResponseTeacher</code>.
   * @alias module:model/TeacherResponseTeacher
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param username {String} 
   * @param email {String} 
   * @param phoneNumber {String} 
   * @param rank {module:model/Rank} 
   * @param totalService {Number} 
   * @param services {Array.<module:model/TeacherResponseTeacherServices>} 
   */
  var exports = function(firstName, lastName, username, email, phoneNumber, rank, totalService, services) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.username = username;
    this.email = email;
    this.phoneNumber = phoneNumber;
    this.rank = rank;
    this.totalService = totalService;
    this.services = services;
  };

  /**
   * Constructs a <code>TeacherResponseTeacher</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeacherResponseTeacher} obj Optional instance to populate.
   * @return {module:model/TeacherResponseTeacher} The populated <code>TeacherResponseTeacher</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
      if (data.hasOwnProperty('rank'))
        obj.rank = Rank.constructFromObject(data['rank']);
      if (data.hasOwnProperty('total_service'))
        obj.totalService = ApiClient.convertToType(data['total_service'], 'Number');
      if (data.hasOwnProperty('services'))
        obj.services = ApiClient.convertToType(data['services'], [TeacherResponseTeacherServices]);
    }
    return obj;
  }

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} username
   */
  exports.prototype.username = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} phoneNumber
   */
  exports.prototype.phoneNumber = undefined;

  /**
   * @member {module:model/Rank} rank
   */
  exports.prototype.rank = undefined;

  /**
   * @member {Number} totalService
   */
  exports.prototype.totalService = undefined;

  /**
   * @member {Array.<module:model/TeacherResponseTeacherServices>} services
   */
  exports.prototype.services = undefined;

  return exports;

}));
