/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Scolendar) {
      root.Scolendar = {};
    }
    root.Scolendar.TeacherResponseTeacherServices = factory(root.Scolendar.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TeacherResponseTeacherServices model module.
   * @module model/TeacherResponseTeacherServices
   * @version v1
   */

  /**
   * Constructs a new <code>TeacherResponseTeacherServices</code>.
   * @alias module:model/TeacherResponseTeacherServices
   * @class
   * @param _class {String} 
   * @param cm {Number} 
   * @param project {Number} 
   * @param td {Number} 
   * @param tp {Number} 
   * @param administration {Number} 
   * @param external {Number} 
   */
  var exports = function(_class, cm, project, td, tp, administration, external) {
    this._class = _class;
    this.cm = cm;
    this.project = project;
    this.td = td;
    this.tp = tp;
    this.administration = administration;
    this.external = external;
  };

  /**
   * Constructs a <code>TeacherResponseTeacherServices</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeacherResponseTeacherServices} obj Optional instance to populate.
   * @return {module:model/TeacherResponseTeacherServices} The populated <code>TeacherResponseTeacherServices</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('class'))
        obj._class = ApiClient.convertToType(data['class'], 'String');
      if (data.hasOwnProperty('cm'))
        obj.cm = ApiClient.convertToType(data['cm'], 'Number');
      if (data.hasOwnProperty('project'))
        obj.project = ApiClient.convertToType(data['project'], 'Number');
      if (data.hasOwnProperty('td'))
        obj.td = ApiClient.convertToType(data['td'], 'Number');
      if (data.hasOwnProperty('tp'))
        obj.tp = ApiClient.convertToType(data['tp'], 'Number');
      if (data.hasOwnProperty('administration'))
        obj.administration = ApiClient.convertToType(data['administration'], 'Number');
      if (data.hasOwnProperty('external'))
        obj.external = ApiClient.convertToType(data['external'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} _class
   */
  exports.prototype._class = undefined;

  /**
   * @member {Number} cm
   */
  exports.prototype.cm = undefined;

  /**
   * @member {Number} project
   */
  exports.prototype.project = undefined;

  /**
   * @member {Number} td
   */
  exports.prototype.td = undefined;

  /**
   * @member {Number} tp
   */
  exports.prototype.tp = undefined;

  /**
   * @member {Number} administration
   */
  exports.prototype.administration = undefined;

  /**
   * @member {Number} external
   */
  exports.prototype.external = undefined;

  return exports;

}));
