/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Scolendar);
  }
}(this, function(expect, Scolendar) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Rank', function() {
      beforeEach(function() {
        instance = Scolendar.Rank;
      });

      it('should create an instance of Rank', function() {
        // TODO: update the code to test Rank
        expect(instance).to.be.a('object');
      });

      it('should have the property MACO', function() {
        expect(instance).to.have.property('MACO');
        expect(instance.MACO).to.be("MACO");
      });

      it('should have the property PROF', function() {
        expect(instance).to.have.property('PROF');
        expect(instance.PROF).to.be("PROF");
      });

      it('should have the property PRAG', function() {
        expect(instance).to.have.property('PRAG');
        expect(instance.PRAG).to.be("PRAG");
      });

      it('should have the property ATER', function() {
        expect(instance).to.have.property('ATER');
        expect(instance.ATER).to.be("ATER");
      });

      it('should have the property PAST', function() {
        expect(instance).to.have.property('PAST');
        expect(instance.PAST).to.be("PAST");
      });

      it('should have the property MONI', function() {
        expect(instance).to.have.property('MONI');
        expect(instance.MONI).to.be("MONI");
      });

    });
  });

}));
