/*
 * Scolendar
 * UE Projet - L3 Informatique AMU 2019-2020 All of the routes missing the `role-professor` or `role-student` tags are meant for administrators only - as stated in their descriptions.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Scolendar);
  }
}(this, function(expect, Scolendar) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('StudentResponseStudent', function() {
      beforeEach(function() {
        instance = new Scolendar.StudentResponseStudent();
      });

      it('should create an instance of StudentResponseStudent', function() {
        // TODO: update the code to test StudentResponseStudent
        expect(instance).to.be.a(Scolendar.StudentResponseStudent);
      });

      it('should have the property firstName (base name: "first_name")', function() {
        // TODO: update the code to test the property firstName
        expect(instance).to.have.property('firstName');
        // expect(instance.firstName).to.be(expectedValueLiteral);
      });

      it('should have the property lastName (base name: "last_name")', function() {
        // TODO: update the code to test the property lastName
        expect(instance).to.have.property('lastName');
        // expect(instance.lastName).to.be(expectedValueLiteral);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

      it('should have the property totalHours (base name: "total_hours")', function() {
        // TODO: update the code to test the property totalHours
        expect(instance).to.have.property('totalHours');
        // expect(instance.totalHours).to.be(expectedValueLiteral);
      });

      it('should have the property subjects (base name: "subjects")', function() {
        // TODO: update the code to test the property subjects
        expect(instance).to.have.property('subjects');
        // expect(instance.subjects).to.be(expectedValueLiteral);
      });

    });
  });

}));
